-- seed-photos.sql — фото от заказчицы (28.06) для туров Камакура/Никко/Симидзу/Фудзи-чай.
-- Фото лежат в public/tours/<slug>/. Точкам присвоены по порядку, остальное — в галерею.

update tours set cover_url='/tours/kamakura/01.jpg', gallery=ARRAY['/tours/kamakura/07.jpg','/tours/kamakura/08.jpg','/tours/kamakura/09.jpg','/tours/kamakura/10.jpg','/tours/kamakura/11.jpg','/tours/kamakura/12.jpg']::text[], stops='[{"text": "Позолоченная статуя 11-головой богини Каннон, фигуры Дзидзо, бамбуковая роща и вид на океан.", "title": "Храм Хасэдэра", "image_query": "Hasedera temple Kamakura", "image_url": "/tours/kamakura/01.jpg"}, {"text": "Бронзовая статуя Будды XIII века под открытым небом.", "title": "Великий Будда Камакуры", "image_query": "Great Buddha Kamakura Daibutsu", "image_url": "/tours/kamakura/02.jpg"}, {"text": "Святилище в природной пещере и легенда о финансовой удаче.", "title": "Святилище Дзэниарай Бэнтэн", "image_query": "Zeniarai Benten shrine Kamakura", "image_url": "/tours/kamakura/03.jpg"}, {"text": "Главное святилище города, род Минамото и первый сёгунат.", "title": "Цуругаока Хатимангу", "image_query": "Tsurugaoka Hachimangu shrine", "image_url": "/tours/kamakura/04.jpg"}, {"text": "Торговая улочка со сладостями и сувенирами.", "title": "Улица Комати-дори", "image_query": "Komachi street Kamakura", "image_url": "/tours/kamakura/05.jpg"}, {"text": "Побережье Камакуры и панорама океана.", "title": "Пляж Юйгахама", "image_query": "Yuigahama beach Kamakura", "image_url": "/tours/kamakura/06.jpg"}]'::jsonb where slug='kamakura';

update tours set cover_url='/tours/nikko/01.jpg', gallery=ARRAY['/tours/nikko/10.jpg','/tours/nikko/11.jpg','/tours/nikko/12.jpg','/tours/nikko/13.jpg','/tours/nikko/14.jpg']::text[], stops='[{"text": "Подземные залы глубиной до 30 метров (Oya History Museum).", "title": "Каменоломни Оя", "image_query": "Oya stone underground quarry Japan", "image_url": "/tours/nikko/01.jpg"}, {"text": "Буддийский храм в скале старше 1000 лет и статуя Каннон.", "title": "Храм Оя-дзи", "image_query": "Oyaji temple rock Buddha Japan", "image_url": "/tours/nikko/02.jpg"}, {"text": "27-метровая статуя, высеченная прямо в скале.", "title": "Статуя Хэйва Каннон", "image_query": "Heiwa Kannon stone statue Oya", "image_url": "/tours/nikko/03.jpg"}, {"text": "Объект ЮНЕСКО: ворота Ёмэймон, «Три обезьяны» и «Спящий кот».", "title": "Храмовый комплекс Тосёгу", "image_query": "Nikko Toshogu shrine Yomeimon", "image_url": "/tours/nikko/04.jpg"}, {"text": "Три священных божества и величественные залы.", "title": "Храм Риннодзи", "image_query": "Rinnoji temple Nikko", "image_url": "/tours/nikko/05.jpg"}, {"text": "Святилище старше 1200 лет в окружении гор.", "title": "Святилище Футарасан", "image_query": "Futarasan shrine Nikko", "image_url": "/tours/nikko/06.jpg"}, {"text": "Один из самых красивых водопадов Японии — 97 метров.", "title": "Водопад Кэгон", "image_query": "Kegon Falls Nikko", "image_url": "/tours/nikko/07.jpg"}, {"text": "Горное озеро у подножия вулкана Нантай.", "title": "Озеро Тюдзэндзи", "image_query": "Lake Chuzenji Nikko", "image_url": "/tours/nikko/08.jpg"}, {"text": "Кварталы эпохи Эдо: дома самураев, шоу ниндзя, ремёсла и костюмы.", "title": "Edo Wonderland Nikko Edomura", "image_query": "Edo Wonderland Nikko Edomura", "image_url": "/tours/nikko/09.jpg"}]'::jsonb where slug='nikko';

update tours set cover_url='/tours/shimizu-fuji-svyatyni/01.jpg', gallery=ARRAY['/tours/shimizu-fuji-svyatyni/05.jpg','/tours/shimizu-fuji-svyatyni/06.jpg','/tours/shimizu-fuji-svyatyni/07.jpg','/tours/shimizu-fuji-svyatyni/08.jpg','/tours/shimizu-fuji-svyatyni/09.jpg','/tours/shimizu-fuji-svyatyni/10.jpg','/tours/shimizu-fuji-svyatyni/11.jpg','/tours/shimizu-fuji-svyatyni/12.jpg']::text[], stops='[{"text": "Смотровая площадка с одним из лучших видов на Фудзи, залив Суруга и холмы Сидзуоки.", "title": "Нихондайра", "image_query": "Nihondaira observation deck Mount Fuji", "image_url": "/tours/shimizu-fuji-svyatyni/01.jpg"}, {"text": "Поездка по канатной дороге к мавзолею сёгуна Токугавы Иэясу.", "title": "Канатная дорога и Кунодзан Тосёгу", "image_query": "Kunozan Toshogu shrine Shizuoka", "image_url": "/tours/shimizu-fuji-svyatyni/02.jpg"}, {"text": "Воссозданное поселение периода Яёй под открытым небом.", "title": "Археологический комплекс Торо", "image_query": "Toro ruins Yayoi village Shizuoka", "image_url": "/tours/shimizu-fuji-svyatyni/03.jpg"}, {"text": "Сосновая аллея ЮНЕСКО и знаменитые открыточные виды на Фудзи.", "title": "Побережье Михо-но-Мацубара", "image_query": "Miho no Matsubara pine grove Fuji", "image_url": "/tours/shimizu-fuji-svyatyni/04.jpg"}]'::jsonb where slug='shimizu-fuji-svyatyni';

update tours set cover_url='/tours/fuji-chay-svyatynya/01.jpg', gallery=ARRAY['/tours/fuji-chay-svyatynya/05.jpg','/tours/fuji-chay-svyatynya/06.jpg','/tours/fuji-chay-svyatynya/07.jpg','/tours/fuji-chay-svyatynya/08.jpg','/tours/fuji-chay-svyatynya/09.jpg','/tours/fuji-chay-svyatynya/10.jpg','/tours/fuji-chay-svyatynya/11.jpg','/tours/fuji-chay-svyatynya/12.jpg']::text[], stops='[{"text": "Изумрудные поля чая на фоне Фудзи; Сидзуока даёт ~40% зелёного чая Японии.", "title": "Чайные плантации Сидзуоки", "image_query": "Shizuoka green tea plantation Mount Fuji", "image_url": "/tours/fuji-chay-svyatynya/01.jpg"}, {"text": "Объект ЮНЕСКО: сотни струй воды, как белоснежная шёлковая завеса.", "title": "Водопад Сираито", "image_query": "Shiraito Falls Fuji Japan", "image_url": "/tours/fuji-chay-svyatynya/02.jpg"}, {"text": "Традиционная японская сакеварня и история рисового виноделия (по желанию).", "title": "Сакеварня и дегустация", "image_query": "Japanese sake brewery tasting", "image_url": "/tours/fuji-chay-svyatynya/03.jpg"}, {"text": "Главное святилище горы Фудзи и духовный центр паломников.", "title": "Fujisan Hongū Sengen Taisha", "image_query": "Fujisan Hongu Sengen Taisha shrine", "image_url": "/tours/fuji-chay-svyatynya/04.jpg"}]'::jsonb where slug='fuji-chay-svyatynya';

-- Обложка для "Старого тракта Токайдо" — старинная почтовая улочка (фото из набора Симидзу/Торо)
update tours set cover_url='/tours/shimizu-fuji-svyatyni/12.jpg' where slug='tokaido-staryy-trakt';
